In [1]:
import numpy as np
import pandas as pd
# from vectorizers import *
# from datasets import InterTASS2019task1Dataset as tass, Melisa2Dataset
import sys
sys.path.append('../')
from utils import *
from pprint import pprint

%load_ext autoreload
%autoreload 2

In [2]:
df_train = tass().get_train_dataframe(lang=['es']).iloc[:5]
df_test = tass().get_train_dataframe(lang=['es']).iloc[11:15].reset_index(drop=True)
df_train['label'] = df_train['label'].replace({'P': 1., 'N': 0.}) 
df_test['label'] = df_test['label'].replace({'P': 1., 'N': 0.}) 
df_train

NameError: name 'tass' is not defined

In [35]:
vec = BONgramsVectorizer(tokenizer=lambda x: x.split(), 
                         min_count=1., max_count=None, 
                         max_words=None, ngram_range=(1,1),
                         vocab=None, 
                         unk_token=None)
X_train = vec.fit_transform(df_train['text'])
X_train = X_train.toarray()
pprint(vec.vocab)
print(X_train)

100%|██████████| 5/5 [00:00<00:00, 14027.77it/s]

{'"cómetelo"': 19,
 '3.': 26,
 '@AlbaBenito99': 8,
 '@Yulian_Poe': 60,
 '@guillermoterry1': 59,
 '@myendlesshazza': 68,
 '@toNi_end': 49,
 'Ah.': 58,
 'JAJAJAJA': 13,
 'Me': 37,
 'Quiero': 18,
 'Vale': 17,
 'a': 3,
 'a.': 33,
 'ahí': 20,
 'b.': 30,
 'basura': 42,
 'bebiendose': 67,
 'bien': 36,
 'contesta': 14,
 'dado': 63,
 'de': 45,
 'dejasen': 46,
 'el': 22,
 'emitir': 44,
 'entendido': 50,
 'esa': 43,
 'escribo': 31,
 'eso': 11,
 'evolucionar': 39,
 'grima': 61,
 'ha': 25,
 'habías': 51,
 'hay': 40,
 'he': 34,
 'help': 27,
 'hs': 64,
 'incluyo.': 52,
 'la': 35,
 'lo': 2,
 'los': 15,
 'mal': 4,
 'me': 5,
 'mejor': 47,
 'mogollón': 7,
 'mucho': 57,
 'muchs': 62,
 'más': 56,
 'para': 38,
 'pero': 9,
 'por': 6,
 'puto': 32,
 'que': 0,
 'quedado': 24,
 'raro': 23,
 'regla': 65,
 'rápido': 12,
 'seria': 48,
 'sigo': 29,
 'sobretodo': 10,
 'solo': 54,
 'su': 66,
 'supuesto!': 55,
 'surrando': 28,
 'tia': 53,
 'visto': 21,
 'wasaps': 16,
 'y': 1,
 'ya': 41}
[[1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 

In [91]:
def test1():
    vec = BONgramsVectorizer(tokenizer=lambda x: x.split(), 
                         min_count=1., max_count=None, 
                         max_words=None, ngram_range=(1,1),
                         vocab=None, 
                         unk_token=None)
    X_train = vec.fit_transform(df_train['text']).toarray()
    inv_vocab = {idx:tk for tk,idx in vec.vocab.items()}
    for j in range(len(df_train['text'])):
        string_tk = df_train['text'][j].split()
        for i, n in enumerate(X_train[j,:]):
            if n != string_tk.count(inv_vocab[i]):
                success = False
                break
            else:
                success = True
    if success:
        print('passed!')
    else:
        print('not passed')
test1()

100%|██████████| 5/5 [00:00<00:00, 8837.56it/s]

passed!


In [90]:
def test2():
    
    vec1 = BONgramsVectorizer(tokenizer=lambda x: x.split(), 
                             min_count=0., max_count=None, 
                             max_words=None, ngram_range=(1,1),
                             vocab=None, 
                             unk_token=None)
    X_train1 = vec1.fit_transform(df_train['text'])
    X_train1 = X_train1.toarray()

    max_freq = df_train['text'].str.split().explode().value_counts()[0]
    
    vec2 = BONgramsVectorizer(tokenizer=lambda x: x.split(), 
                             min_count=1., max_count=max_freq, 
                             max_words=None, ngram_range=(1,1),
                             vocab=None, 
                             unk_token=None)
    X_train2 = vec2.fit_transform(df_train['text'])
    X_train2 = X_train2.toarray()
    
    vec3 = BONgramsVectorizer(tokenizer=lambda x: x.split(), 
                             min_count=1., max_count=max_freq-1, 
                             max_words=None, ngram_range=(1,1),
                             vocab=None, 
                             unk_token=None)
    X_train3 = vec3.fit_transform(df_train['text'])
    X_train3 = X_train3.toarray()
    
    if (np.array_equal(X_train1,X_train2)) and not (np.array_equal(X_train1,X_train3)):
        print('passed!')
    else:
        print('not passed')

test2()

100%|██████████| 5/5 [00:00<00:00, 14074.85it/s]

[[0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 1 2 0 0 1 1 1 1 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
passed!


In [2]:
df_train = Melisa2Dataset().get_train_dataframe(usecols=['review_content','review_rate']).sample(n=10,random_state=0).reset_index(drop=True)
df_train['review_content'] = df_train['review_content'].str.lower()
df_val = Melisa2Dataset().get_train_dataframe(usecols=['review_content','review_rate']).sample(n=10,random_state=72384).reset_index(drop=True)
df_val['review_content'] = df_val['review_content'].str.lower()
df_train

review_content  review_rate
0  excelente producto pues el material es metálic...            1
1  los almohadones son muy lindos y se adecúan mu...            1
2                lo que buscaba en precio y calidad.            0
3  funciona como esta descrito, buena sincronizac...            1
4  conozco el q cuesta un 60% mas y la unica dife...            1
5  no era lo que esperaba, no sirven para metal, ...            0
6  el producto cumple con las expectativas. ya se...            1
7  muy bonitas y bien construidas. contento con l...            1
8  estoy muy contento. tuve que hacer unos ajuste...            1
9  producto malo , la chapa parece de lata de pic...            0

In [23]:
from nltk import word_tokenize

vec = BONgramsVectorizer(tokenizer=word_tokenize, 
                          min_count=0., max_count=None, 
                          max_words=100, ngram_range=(1,2),
                          vocab=None, unk_token=None)

X_train = vec.fit_transform(df_train['review_content']).toarray()
print(X_train)
vec.vocab

100%|██████████| 10/10 [00:00<00:00, 1115.33it/s]

[[1 2 0 1 1 0 2 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0
  0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [4 4 2 4 3 5 1 0 0 2 3 0 0 1 2 2 1 2 2 0 0 2 1 1 0 0 2 1 0 0 0 1 0 0 0 0
  1 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 2 0 2 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0]
 [3 0 1 2 2 1 1 1 2 2 0 2 0 2 1 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 0 1 0 0 0 0 0 0 0 

{'.': 0,
 ',': 1,
 'de': 2,
 'y': 3,
 'la': 4,
 'muy': 5,
 'el': 6,
 'que': 7,
 'no': 8,
 'es': 9,
 'las': 10,
 'en': 11,
 'lo': 12,
 'se': 13,
 'bien': 14,
 'calidad': 15,
 'con': 16,
 'los': 17,
 'muy bien': 18,
 'para': 19,
 '. en': 20,
 'son': 21,
 'con la': 22,
 'a': 23,
 'tener': 24,
 'producto': 25,
 ', y': 26,
 ', las': 27,
 'precio': 28,
 'un': 29,
 'no lo': 30,
 'por': 31,
 'resistente': 32,
 'lo que': 33,
 'contento': 34,
 'era': 35,
 'buena': 36,
 'mi': 37,
 'en relacion': 38,
 'material': 39,
 'ya': 40,
 'compra': 41,
 'compra .': 42,
 'la compra': 43,
 'el material': 44,
 'malo': 45,
 'varios': 46,
 'si': 47,
 '. el': 48,
 'potencia': 49,
 'estoy': 50,
 'o': 51,
 'me': 52,
 'solo': 53,
 'tengo': 54,
 ', no': 55,
 'relacion': 56,
 'tienen': 57,
 'el q': 58,
 'minutos': 59,
 '10': 60,
 'arma': 61,
 'madera': 62,
 'firme': 63,
 'conozco el': 64,
 'diferencia': 65,
 've': 66,
 'q cuesta': 67,
 'super': 68,
 'plastico': 69,
 'tan': 70,
 'tiene': 71,
 'bordes': 72,
 'menos': 73

In [29]:
vocab = ['.',',','de','y','la','muy','el','que','no','es','las','en','lo','se']

vec1 = BONgramsVectorizer(tokenizer=word_tokenize, 
                          min_count=0., max_count=None, 
                          max_words=100, ngram_range=(1,3),
                          vocab=vocab, unk_token=None)

X_train1 = vec1.fit_transform(df_train['review_content']).toarray()

vec2 = BONgramsVectorizer(tokenizer=word_tokenize, 
                          min_count=0., max_count=None, 
                          max_words=100, ngram_range=(1,3),
                          vocab=vocab, unk_token='UNK')

X_train2 = vec2.fit_transform(df_train['review_content']).toarray()
X_train2[:,1:] == X_train1

100%|██████████| 10/10 [00:00<00:00, 667.56it/s]
<ipython-input-29-f74ba17fe69c>:16: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  X_train2[1:,:] == X_train1


False

In [53]:
vec = BONgramsVectorizer(tokenizer=word_tokenize, 
                          min_count=0., max_count=None, 
                          max_words=20, ngram_range=(1,1),
                          vocab=['coso','pituto','el','cosito'], unk_token=None)

X_train = vec.fit_transform(df_train['review_content']).toarray()
X_train
vec.vocab

100%|██████████| 10/10 [00:00<00:00, 1481.46it/s]

excelente 1
producto 1
pues 1
el 1
material 1
es 1
metálico 1
y 1
resistente 1
, 1
durabilidad 1
comprobada 1
calza 1
a 1
la 1
perfección 1
en 1
optra 1
designe 1
. 1
los 1
almohadones 1
son 1
muy 1
lindos 1
se 1
adecúan 1
bien 1
las 1
sillas 1
fundas 1
excelentes 1
por 1
calidad 1
de 1
tela 1
costuras 1
fuertes 1
cierres 1
terminados 1
relleno 1
buena 1
cómodo 1
mullido 1
quedamos 1
conformes 1
con 1
compra 1
lo 1
que 1
buscaba 1
precio 1
funciona 1
como 1
esta 1
descrito 1
sincronizacion 1
bluetooth 1
varios 1
modos 1
transición 1
llamativo 1
pero 1
falto 1
potencia 1
claridad 1
esperada 1
conozco 1
q 1
cuesta 1
un 1
60 1
% 1
mas 1
unica 1
diferencia 1
madera 1
no 1
ve 1
tan 1
tiene 1
bordes 1
plastico 1
super 1
firme 1
relacion 1
arma 1
10 1
minutos 1
o 1
menos 1
era 1
esperaba 1
sirven 1
para 1
metal 1
solo 1
tengo 1
adorno 1
cumple 1
expectativas 1
ya 1
sabe 1
está 1
comprando 1
algo 1
económico 1
mi 1
caso 1
idea 1
tener 1
reproductor 1
liviano 1
todo 1
terreno 1
me 1
importe 1
s

{'el': 0}

In [44]:
X_val = vec.transform(df_val['review_content']).toarray()
X_val

100%|██████████| 10/10 [00:00<00:00, 1729.25it/s]


array([[57,  3],
       [92,  2],
       [41,  2],
       [18,  0],
       [15,  0],
       [47,  1],
       [15,  1],
       [12,  0],
       [53,  0],
       [15,  0]])

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

vec2 = CountVectorizer(tokenizer=word_tokenize,
                       max_features=20,ngram_range=(1,2),
                       vocabulary=['coso','pituto','el','cosito'])

X_train = vec2.fit_transform(df_train['review_content']).toarray()
X_train

array([[0, 0, 2, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 1, 0],
       [0, 0, 3, 0],
       [0, 0, 1, 0]])

In [13]:
y_train = np.array([1,0,0,1,0,1,1,1,0,0],dtype=float)
y_train = y_train.astype(int)
y_one_hot = np.zeros((y_train.size,y_train.max()+1),dtype=float)
y_one_hot[np.arange(y_train.size),y_train] = 1.

X = np.array([[0, 0, 2, 0],
               [1, 0, 1, 0],
               [0, 3, 0, 0],
               [0, 0, 0, 0],
               [1, 0, 1, 1],
               [0, 0, 0, 0],
               [0, 0, 2, 0],
               [4, 2, 1, 3],
               [0, 0, 3, 0],
               [0, 0, 1, 0]])
from scipy.sparse import csr_matrix
X = csr_matrix(X)

X.dot(X.minimum(1).T.dot(y_one_hot))
print(W)
X.dot(W)


[[5. 8.]
 [7. 6.]
 [7. 7.]
 [5. 7.]]


array([[14., 14.],
       [12., 15.],
       [21., 18.],
       [ 0.,  0.],
       [17., 22.],
       [ 0.,  0.],
       [14., 14.],
       [56., 72.],
       [21., 21.],
       [ 7.,  7.]])

In [12]:
df_train = Melisa2Dataset().get_train_dataframe(usecols=['review_content','review_rate'])#.sample(n=10000,random_state=0).reset_index(drop=True)
df_train['review_content'] = df_train['review_content'].str.lower()
df_val = Melisa2Dataset().get_train_dataframe(usecols=['review_content','review_rate'])#.sample(n=10000,random_state=72384).reset_index(drop=True)
df_val['review_content'] = df_val['review_content'].str.lower()

In [13]:
vec = WordByCategoryCBOWVectorizer()
X_train = vec.fit_transform(df_train['review_content'],df_train['review_rate'])
X_train

array([[ 767573.,  888766.],
       [1138319., 1909307.],
       [1580805., 2728291.],
       ...,
       [ 334374.,  473914.],
       [1924806., 3430821.],
       [1114427., 1977380.]])

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk import word_tokenize
from collections import defaultdict
from torch.nn.utils.rnn import pack_sequence
import torch

vec = CountVectorizer(tokenizer=word_tokenize)
corpus = ['Mi casa es muy linda', 'Mi casa también es muy linda']
X = vec.fit_transform(corpus)
tokenize = vec.build_analyzer()
vocab = defaultdict(lambda : -1,vec.vocabulary_)
idx_seqs = [torch.tensor([vocab[tk] for tk in tokenize(text)]) for text in corpus]
pack_sequence(idx_seqs)

PackedSequence(data=tensor([3, 3, 0, 0, 5, 1, 1, 4, 4, 2, 2]), batch_sizes=tensor([2, 2, 2, 2, 2, 1]), sorted_indices=tensor([1, 0]), unsorted_indices=tensor([1, 0]))

In [55]:
import pandas as pd
ds = pd.Series(['Mi casa es muy linda', 'Mi casa también es muy linda'])
ds.str.len().argsort()[::-1]

array([1, 0])

In [3]:
df_train = Melisa2Dataset().get_train_dataframe(usecols=['review_content','review_rate']).sample(n=10,random_state=0).reset_index(drop=True)
df_train['review_content'] = df_train['review_content'].str.lower()
df_val = Melisa2Dataset().get_train_dataframe(usecols=['review_content','review_rate']).sample(n=10,random_state=72384).reset_index(drop=True)
df_val['review_content'] = df_val['review_content'].str.lower()
df_train

review_content  review_rate
0  excelente producto pues el material es metálic...            1
1  los almohadones son muy lindos y se adecúan mu...            1
2                lo que buscaba en precio y calidad.            0
3  funciona como esta descrito, buena sincronizac...            1
4  conozco el q cuesta un 60% mas y la unica dife...            1
5  no era lo que esperaba, no sirven para metal, ...            0
6  el producto cumple con las expectativas. ya se...            1
7  muy bonitas y bien construidas. contento con l...            1
8  estoy muy contento. tuve que hacer unos ajuste...            1
9  producto malo , la chapa parece de lata de pic...            0

In [45]:
class Word2IndexVectorizer(object):

    def __init__(self,*args,**kwargs):
        self.vec = CountVectorizer(*args,**kwargs)
        self.tokenize = self.vec.build_analyzer()

    def fit_transform(self,ds_train):
        self.vec.fit(ds_train)
        vocab = defaultdict(lambda : -1,self.vec.vocabulary_)
        self.vocab = vocab
        ds_train = ds_train.apply(self.tokenize)
        sorted_idx = ds_train.str.len().argsort()
        idx_seqs = np.array([torch.tensor([vocab[tk] for tk in text]) for text in ds_train],dtype=object)
        idx_seqs = idx_seqs[sorted_idx][::-1]
        seqs = pack_sequence(idx_seqs)
        return seqs

    def transform(self,ds_test):
        ds_train = ds_train.apply(self.tokenize)
        sorted_idx = ds_train.str.len().argsort()
        idx_seqs = np.array([torch.tensor([vocab[tk] for tk in text]) for text in ds_train],dtype=object)
        idx_seqs = idx_seqs[sorted_idx][::-1]
        seqs = pack_sequence(idx_seqs)
        return seqs
        
from nltk import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from collections import defaultdict
import torch
from torch.nn.utils.rnn import pack_sequence, pad_packed_sequence
import torch.nn as nn
        
vec = Word2IndexVectorizer(tokenizer=word_tokenize)
packed_seq = vec.fit_transform(df_train['review_content'])
padded_seq, lenghts = pad_packed_sequence(packed_seq,batch_first=True)

padded_seq.to(device=torch.device('cpu'))
# emb = nn.Embedding(len(vec.vocab),2)
# emb(padded_seq).size()
#padded_seq

tensor([[ 65, 141,  54,  44,  97,  81,   6, 193, 157, 156, 144, 157,  78,  40,
          15, 122,  64,   6,  66, 118,  33,  96,  91,  68, 171, 183, 152, 122,
         100, 179, 174, 192, 144, 124, 113,  94, 158, 172,  96, 108, 166,  56,
         132, 127,  56, 144, 113, 102, 155,   6,  69,  93,  41,  19,  22,  56,
         114,  30, 193, 144, 103, 144, 180,  65,  67, 124, 102, 164,   6],
        [122,  25, 192,  23,  49,   6,  50,  44,  96,  39,   6,  47, 129, 146,
          97,  42,  10, 191,  23,  65,  70, 144, 147,  92,   5,  74,  18,   5,
         124, 176,  88, 139, 105,   5,  66,  87,  76, 178,   2,   1, 126, 176,
           6, 158, 163, 188,  11, 171,  56,  75, 177,  56,  17,   5,  48, 184,
         106,  56, 189, 165,   3,  56,   8,  90,  21,   4,   6,   0,   0],
        [103,  16, 164, 122,  99, 192, 157,  12, 122,  23,  11,  97, 159,   6,
          97,  86, 164,  80, 138,  96,  30,  56,  96, 170,   5,  97,  52,  84,
           5, 103,  36,   5, 192, 122,  23, 173,   6,  65, 1

In [51]:
emb = nn.Embedding(4,2,padding_idx=-1)
emb(torch.tensor([[0,0,0,3],[1,1,1,-1]]))

IndexError: index out of range in self